version: '3'
services:
  cities_bot:
    image: cities_bot
    environment:
      APP: app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    tty: true
  mongodb:
    image: "mongo:latest"
