version: '3'
services:
  cities_bot:
    image: cities_bot
    environment:
      APP: app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb
    tty: true
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    command: ["mongod", "--smallfiles", "--logpath=/dev/null"]
  migration:
    image: cities_bot:latest
    command: ["python3", "migration/mongo.py"]
    depends_on:
     - mongodb
